name: Update README

on:
  push:
    paths:
      - '**/*'  # Trigger on any file change

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # 4. Generate README
      - name: Generate README
        run: python generate_readme.py

      # 5. Commit and push changes
      - name: Commit and push README
        run: |
          git config --global user.name "piyaphat bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update README automatically"
          git push
